### ISSUE TITLE
Use game_text to show current Chaos effects(and timer)

### ISSUE THREAD

**Issue by cytrus224** [b0ink/csgo-chaos-mod#2]
Hey, i tried your plugin and the idea is great, however it kinda sucks to see chaos effects only announced in the chat. Would be great if you could show it with game_text. Also add dynamicchannels support if you can. Thanks! https://github.com/Vauff/DynamicChannels

**Comment by b0ink** [comment]
This is exactly what I've been looking for!

I've made a visible timer for the Effect Interval countdown just below the round time as well as a list of current effects with their individual timers on the left of the screen. I'll have to go through and optimise a few of the effect names to make sure they don't cover any screens on smaller resolutions

Thanks!
