### ISSUE TITLE
Replace HUD with HTML5 Method

### ISSUE THREAD

**Issue by SteveBox0** [b0ink/csgo-chaos-mod#4]
Instead of using HUD that does not work at all resolutions use the Backwards HTML method instead. 

https://forums.alliedmods.net/showthread.php?t=326935

**Comment by b0ink** [comment]
Unfortunately the limitation with this method is that there's a 1 second delay from sending the event and that there has to be a minimum 1 second buffer before sending the event again to refresh it. You're also limited to the centre of the screen so at this stage I have added an option to enable this method only for effect announcements, I might have to look into other options for the effect list and effect timer, such as using HintText.

Thanks for the suggestion!
