### ISSUE TITLE
crash on dedicated server with lasted version

### ISSUE THREAD

**Issue by caiweilv** [b0ink/csgo-chaos-mod#5]
Wonderful plugin but there's a chance to crash
//
L 05/14/2023 - 15:17:49: [SM] Exception reported: Script execution timed out
L 05/14/2023 - 15:17:49: [SM] Blaming: Chaos.smx
L 05/14/2023 - 15:17:49: [SM] Call stack trace:
L 05/14/2023 - 15:17:49: [SM]   [1] Line 242, Effects\Effect.sp::IsChaosEffectRunning
L 05/14/2023 - 15:17:49: [SM]   [2] Line 165, Effects\Effect.sp::IsCompatible
L 05/14/2023 - 15:17:49: [SM]   [3] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/14/2023 - 20:01:55: Error log file session closed.

//
L 05/15/2023 - 09:52:06: [SM] Exception reported: Entity 669 (669) is not a CBaseEntity
L 05/15/2023 - 09:52:06: [SM] Blaming: Chaos.smx
L 05/15/2023 - 09:52:06: [SM] Call stack trace:
L 05/15/2023 - 09:52:06: [SM]   [0] AcceptEntityInput
L 05/15/2023 - 09:52:06: [SM]   [1] Line 131, Global\Fog.sp::Fog_OFF
L 05/15/2023 - 09:52:06: [SM]   [2] Line 276, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ResetRoundChaos
L 05/15/2023 - 09:52:06: [SM]   [3] Line 185, Events.sp::ResetChaos
L 05/15/2023 - 09:52:06: [SM]   [4] Line 39, Forwards.sp::OnPluginEnd
L 05/15/2023 - 09:52:06: Error log file session closed.

//
L 05/13/2023 - 16:51:48: [SM] Exception reported: Script execution timed out
L 05/13/2023 - 16:51:48: [SM] Blaming: Chaos.smx
L 05/13/2023 - 16:51:48: [SM] Call stack trace:
L 05/13/2023 - 16:51:48: [SM]   [0] Call_Finish
L 05/13/2023 - 16:51:48: [SM]   [1] Line 100, Effects\Effect.sp::CanRunEffect
L 05/13/2023 - 16:51:48: [SM]   [2] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/13/2023 - 16:52:20: [SM] Exception reported: Script execution timed out
L 05/13/2023 - 16:52:20: [SM] Blaming: Chaos.smx
L 05/13/2023 - 16:52:20: [SM] Call stack trace:
L 05/13/2023 - 16:52:20: [SM]   [1] Line 181, Effects\Effect.sp::IsCompatible
L 05/13/2023 - 16:52:20: [SM]   [2] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
//

L 05/12/2023 - 20:02:13: Error log file session closed.
L 05/12/2023 - 20:56:59: SourceMod error session started
L 05/12/2023 - 20:56:59: Info (map "de_inferno_destruct") (file "/home/csgo/serverfiles/csgo/addons/sourcemod/logs/errors_20230512.log")
L 05/12/2023 - 20:56:59: [SM] Exception reported: Script execution timed out
L 05/12/2023 - 20:56:59: [SM] Blaming: Chaos.smx
L 05/12/2023 - 20:56:59: [SM] Call stack trace:
L 05/12/2023 - 20:56:59: [SM]   [1] Line 172, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/12/2023 - 21:57:02: Error log file session closed.
L 05/12/2023 - 22:51:43: SourceMod error session started
L 05/12/2023 - 22:51:43: Info (map "de_inferno_destruct") (file "/home/csgo/serverfiles/csgo/addons/sourcemod/logs/errors_20230512.log")
L 05/12/2023 - 22:51:43: [SM] Exception reported: Script execution timed out
L 05/12/2023 - 22:51:43: [SM] Blaming: Chaos.smx
L 05/12/2023 - 22:51:43: [SM] Call stack trace:
L 05/12/2023 - 22:51:43: [SM]   [0] Call_Finish
L 05/12/2023 - 22:51:43: [SM]   [1] Line 100, Effects\Effect.sp::CanRunEffect
L 05/12/2023 - 22:51:43: [SM]   [2] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/12/2023 - 22:52:15: [SM] Exception reported: Script execution timed out
L 05/12/2023 - 22:52:15: [SM] Blaming: Chaos.smx
L 05/12/2023 - 22:52:15: [SM] Call stack trace:
L 05/12/2023 - 22:52:15: [SM]   [0] Call_Finish
L 05/12/2023 - 22:52:15: [SM]   [1] Line 100, Effects\Effect.sp::CanRunEffect
L 05/12/2023 - 22:52:15: [SM]   [2] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/12/2023 - 22:52:15: [SM] Exception reported: Invalid index 0 (count: 0)
L 05/12/2023 - 22:52:15: [SM] Blaming: Chaos.smx
L 05/12/2023 - 22:52:15: [SM] Call stack trace:
L 05/12/2023 - 22:52:15: [SM]   [0] GetArrayCell
L 05/12/2023 - 22:52:15: [SM]   [1] Line 154, Helpers.sp::GetRandomAlivePlayer
L 05/12/2023 - 22:52:15: [SM]   [2] Line 184, Effects\Game\AutoPlantC4.sp::AutoPlantC4
L 05/12/2023 - 22:52:15: [SM]   [3] Line 78, Effects\Game\AutoPlantC4.sp::Chaos_AutoPlantC4_START
L 05/12/2023 - 22:52:15: [SM]   [5] Call_Finish
L 05/12/2023 - 22:52:15: [SM]   [6] Line 68, Effects\Effect.sp::Run
L 05/12/2023 - 22:52:15: [SM]   [7] Line 163, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/12/2023 - 22:52:47: [SM] Exception reported: Script execution timed out
L 05/12/2023 - 22:52:47: [SM] Blaming: Chaos.smx
L 05/12/2023 - 22:52:47: [SM] Call stack trace:
L 05/12/2023 - 22:52:47: [SM]   [1] Line 242, Effects\Effect.sp::IsChaosEffectRunning
L 05/12/2023 - 22:52:47: [SM]   [2] Line 165, Effects\Effect.sp::IsCompatible
L 05/12/2023 - 22:52:47: [SM]   [3] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/12/2023 - 22:56:03: Error log file session closed.
L 05/12/2023 - 23:51:27: SourceMod error session started
L 05/12/2023 - 23:51:27: Info (map "de_inferno_destruct") (file "/home/csgo/serverfiles/csgo/addons/sourcemod/logs/errors_20230512.log")
L 05/12/2023 - 23:51:27: [SM] Exception reported: Script execution timed out
L 05/12/2023 - 23:51:27: [SM] Blaming: Chaos.smx
L 05/12/2023 - 23:51:27: [SM] Call stack trace:
L 05/12/2023 - 23:51:27: [SM]   [1] Line 202, Effects\Effect.sp::IsCompatible
L 05/12/2023 - 23:51:27: [SM]   [2] Line 154, f:\Sourcepawn\scripting\csgo-chaos-mod\addons\sourcemod\scripting\Chaos.sp::ChooseEffect
L 05/13/2023 - 10:07:10: Error log file session closed.

**Comment by caiweilv** [comment]
after recompiled
L 05/17/2023 - 12:17:02: SourceMod error session started
L 05/17/2023 - 12:17:02: Info (map "de_inferno_destruct") (file "/home/csgo/serverfiles/csgo/addons/sourcemod/logs/errors_20230517.log")
L 05/17/2023 - 12:17:02: [SM] Exception reported: Script execution timed out
L 05/17/2023 - 12:17:02: [SM] Blaming: Chaos.smx
L 05/17/2023 - 12:17:02: [SM] Call stack trace:
L 05/17/2023 - 12:17:02: [SM]   [0] Call_Finish
L 05/17/2023 - 12:17:02: [SM]   [1] Line 100, Effects/Effect.sp::CanRunEffect
L 05/17/2023 - 12:17:02: [SM]   [2] Line 162, Chaos.sp::ChooseEffect
L 05/17/2023 - 12:18:10: [SM] Exception reported: Script execution timed out
L 05/17/2023 - 12:18:10: [SM] Blaming: Chaos.smx
L 05/17/2023 - 12:18:10: [SM] Call stack trace:
L 05/17/2023 - 12:18:10: [SM]   [1] Line 187, Effects/Effect.sp::IsCompatible
L 05/17/2023 - 12:18:10: [SM]   [2] Line 162, Chaos.sp::ChooseEffect

//
L 05/17/2023 - 12:17:02: [Chaos.smx] Triggering effect: Chaos_ExtendC4Timer
L 05/17/2023 - 12:17:13: [Chaos.smx] Triggering effect: Chaos_1v1
L 05/17/2023 - 12:17:37: [Chaos.smx] Triggering effect: Chaos_SwapEnemyWeapons

**Comment by b0ink** [comment]
I think I've been able to replicate the same error, can you confirm that you've copied over the `configs` folder to your server, ensuring that `addons/sourcemod/configs/Chaos/Chaos_Convars.cfg` exists on your server? (Also ensure that you've copied over the `data`, `gamedata` and `translations` folder contents too)

It looks like if the config is missing the interval between each effect doesn't get set so it defaults to `0` instead of `15`, endlessly triggering a new effect with no delay before timing out the server

If that fixes it for you I'll push a fix shortly to default the interval to `15`

**Comment by caiweilv** [comment]
I'll reinstall the whole plugin and give feedback soon。 thanks for your working

**Comment by b0ink** [comment]
Closing this assuming that fixed your issue, please open a new one if your issue persists
