### ISSUE TITLE
forwards are not executed

### ISSUE THREAD

**Issue by daffyyyy** [b0ink/csgo-chaos-mod#7]
Hi,
Forwards like `OnGameFrame, OnPlayerRunCmd` and probably others not execute after effect run.
Example effect: Double Jump

Problem probably here
```	
Format(function_name, sizeof(function_name), "%s_OnGameFrame", EffectNames[i]);
effect.OnGameFrame = GetFunctionByName(GetMyHandle(), function_name);
```` 
but when changed to 
`effect.OnGameFrame = Chaos_DoubleJump_OnGameFrame;`
Effect works

**Comment by b0ink** [comment]
Hi,
I can't quite understand what issue you're facing - could you please provide any more details or error logs (if any)?

Running the latest version of Chaos Mod, the Double Jump effect works with no issues, confirming that OnGameFrame is executed correctly while the effect is active. For clarification, effect's forwards such as `OnGameFrame` and `OnPlayerRunCmd` are only run while the effect is active, and once the effect ends those forwards will no longer be executed.

If you are attempting to [create your own effect](https://github.com/b0ink/csgo-chaos-mod/wiki/Creating-New-Effects-%5BWIP%5D#additional-forwards) with those forwards, you can use `effect.RunForwardWhileInactive("OnGameFrame")`  in your effect [setup function](https://github.com/b0ink/csgo-chaos-mod/wiki/Creating-New-Effects-%5BWIP%5D#setup) to force the forwards to be run without the effect being active

**Comment by daffyyyy** [comment]
Set `sm_chaos_override_duration` to `0` and check if doublejump works.
default is `-1` and then it works but when `0` it doesn't work

**Comment by b0ink** [comment]
Ahh nice catch, I will push a fix for this shortly

In the mean time you can set it to its max value of 120 seconds, which should almost achieve the same result of having the effects last all round, assuming your round time doesn't exceed 2 minutes

Thanks

**Comment by b0ink** [comment]
A timer of 3600 seconds is now created when the ConVar is set to 0, allowing for forwards to work correctly
Long timer duration is used to allow for more than enough time in deathmatch/co-op game modes

Thanks again!
